### ISSUE TITLE
Collision Issue with Cone Mesh bottom

### ISSUE THREAD

**Issue by blitzcoder** [angros47/OpenB3D#12]
When trying out a port of the [EntityRadius example](https://kippykip.com/b3ddocs/commands/3d_commands/EntityRadius.htm), I found a small issue when colliding a mesh at the bottom or base part of the cone mesh (`CreateCone`). 

The colliding mesh disappears instead of any of the 3 responses, even when the cone is set as solid.

**Comment by angros47** [comment]
I tried to reproduce the issue: the colliding mesh disappears _only_ when the cone is set as solid (by default the cone should be set as solid, unless you set the second parameter to zero). If the cone is not solid, the colliding mesh goes through the bottom, as it's supposed to do.

Also, the issue doesn't happen if the collision radius is reduced.
By using a cylinder instead of a cone, the issue doesn't happen, either.

Can you confirm all of that?

The reason the colliding mesh disappears seems to be that its coordinates change to "-nan" (Not A Number), and that makes me think some division by zero happens somewhere.

**Comment by angros47** [comment]
Ok, I found an imperfection in how the cone mesh is generated (one triangle in the base is redundant). I modified the file "mesh.cpp" with the fix. Try recompiling the library with that change, and let me know if it fixes the issue.

**Comment by blitzcoder** [comment]
Ok so the disappearing behavior confirmed to be a bug since it should just passed through if it is not set as solid.

Yes, I was using default params with CreateCone so it is solid, but works great now with the fix. closing.
