### ISSUE TITLE
Add AntiAlias and TrisRendered

### ISSUE THREAD

**Issue by blitzcoder** [angros47/OpenB3D#3]
You might be interested on these 2 functions that [Mark](https://github.com/markcwm/) has added  in his modified sources with the AntiAlias using accum. buffer and TrisRendered functions.

**Comment by angros47** [comment]
I knew about those changes, and I haven't implemented because I thought they would cause more issues than advantages:

- AntiAlias would create issues with particle trails, since the trails are updated every time the picture is rendered. Also, I think it's pretty useless, since antialias can be achieved using the parameter GL_MULTISAMPLE:
https://stackoverflow.com/questions/10508872/opengl-antialiasing-without-the-accumulation-buffer
It is faster, simpler, and has the advantage that, if used on a version of OpenGL that doesn't support it, it would just be ignored and rendering with no antialias will be performed.

- TrisRendered does not return the real number of triangles rendered: it counts all the triangles used in the meshes rendered by a specified camera, but it doesn't count the triangles included in terrains, geospheres, or isosurfaces (and that number is much more important, since those entities are generated dynamically at each frame and the number of triangles changes). So, if you have even one terrain in the scene, the number of triangles returned by TrisRendered is wrong.

**Comment by blitzcoder** [comment]
Ok I see. I already have added TrisRendered for the time being and also planning to add AntiAlias and then just update or improve on these eventually. I do have a few AA shaders posted perhaps make one of them embedded or built-in.
